/** Declaration file generated by dts-gen */

export = gitrows;

declare class gitrows {
    constructor(...args: any[]);

    columns(...args: any[]): void;

    create(...args: any[]): void;

    delete(...args: any[]): void;

    drop(...args: any[]): void;

    get(...args: any[]): void;

    options(...args: any[]): void;

    pull(...args: any[]): void;

    push(...args: any[]): void;

    put(...args: any[]): void;

    replace(...args: any[]): void;

    reset(...args: any[]): void;

    test(...args: any[]): void;

    types(...args: any[]): void;

    update(...args: any[]): void;

}

